# Generated by Django 5.2.7 on 2025-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
