# Generated by Django 5.2.7 on 2025-12-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='TZS', max_length=100),
            preserve_default=False,
        ),
    ]
