# Generated by Django 5.2.7 on 2025-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Tecno spark 10 is a powerful and stable android phone which guarentees power 24 hours a day'),
            preserve_default=False,
        ),
    ]
